/*
* generated by Xtext
*/
package org.eclipse.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.services.ClassdefGrammarAccess;

public class ClassdefParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ClassdefGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.xtext.parser.antlr.internal.InternalClassdefParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xtext.parser.antlr.internal.InternalClassdefParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ClassDefinitions";
	}
	
	public ClassdefGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ClassdefGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
