/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.ui.internal.ClassdefActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ClassdefExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ClassdefActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ClassdefActivator.getInstance().getInjector(ClassdefActivator.ORG_ECLIPSE_XTEXT_CLASSDEF);
	}
	
}
