/*
* generated by Xtext
*/
package org.eclipse.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ClassdefUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.xtext.ui.internal.ClassdefActivator.getInstance().getInjector("org.eclipse.xtext.Classdef");
	}
	
}
