language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: cd TODO_Example_Xtext2/releng/org.eclipse.xtext.todo.distribution && mvn clean -B -V deploy -Pmodules-default,modules-assembly -Dgithub.site.dryRun=true
env:
  global:
    secure: axvjtAqhdh32g9zmUaxd4mu7+iR/ZJaj/hw+Ss5XMJDcCKUSR/BUvqvo7ZFeHN2YGwS8DzCS0Fsr6Axop5mqfzyjVvHDKd4zE+Lm7HW+NUJVoV8khlLeEVX/KYcqWkKNkChxRRbIB3xnqim1H4T2ThKNlzl3wHgFRXdzK/gl57c=
