/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.parser.IEncodingProvider;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.service.DispatchingProvider;
import org.xtext.example.mydsl.encoding.UTF8Provider;
import org.xtext.example.mydsl.resources.MyDslResourceDescriptionStrategy;
import org.xtext.example.mydsl.scoping.PackageSelector;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class MyDslRuntimeModule extends
		org.xtext.example.mydsl.AbstractMyDslRuntimeModule {

	@Override
	public void configureRuntimeEncodingProvider(Binder binder) {
		binder.bind(IEncodingProvider.class)
				.annotatedWith(DispatchingProvider.Runtime.class)
				.to(UTF8Provider.class);
	}
	
	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return MyDslResourceDescriptionStrategy.class;
	}

	public Class<? extends PackageSelector> bindPackageSelector() {
		return PackageSelector.class;
	}
}
