/*
* generated by Xtext
*/
package org.eclipse.xtext.ui.contentassist;

import org.eclipse.xtext.ui.contentassist.AbstractClassdefProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ClassdefProposalProvider extends AbstractClassdefProposalProvider {

}
