/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ClassdefUiModule extends org.eclipse.xtext.ui.AbstractClassdefUiModule {
	public ClassdefUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
