/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.parser.IEncodingProvider;
import org.eclipse.xtext.service.DispatchingProvider;
import org.xtext.example.mydsl.encoding.UTF8Provider;
import org.xtext.example.mydsl.ui.contentassist.CustomReferenceProposalCreator;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends
		org.xtext.example.mydsl.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configureUiEncodingProvider(Binder binder) {
		binder.bind(IEncodingProvider.class)
				.annotatedWith(DispatchingProvider.Ui.class)
				.to(UTF8Provider.class);
	}

	public Class<? extends IEncodingProvider> bindIEncodingProvider() {
		return UTF8Provider.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator> bindAbstractJavaBasedContentProposalProvider$ReferenceProposalCreator() {
		return CustomReferenceProposalCreator.class;
	}
}
