/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.parser.IEncodingProvider;
import org.eclipse.xtext.service.DispatchingProvider;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.xtext.example.mydsl.encoding.UTF8Provider;
import org.xtext.example.mydsl.ui.contentassist.CustomReferenceProposalCreator;
import org.xtext.example.mydsl.ui.highlighting.MyDslHighlightingConfiguration;
import org.xtext.example.mydsl.ui.highlighting.MyDslSemanticHighlightingCalculator;
import org.xtext.example.mydsl.ui.tasks.ITaskElementChecker;
import org.xtext.example.mydsl.ui.tasks.MyDslTaskElementChecker;
import org.xtext.example.mydsl.ui.tasks.TaskConstants;
import org.xtext.example.mydsl.ui.tasks.XtextTaskCalculator;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends
		org.xtext.example.mydsl.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return MyDslSemanticHighlightingCalculator.class;
	}

	public Class<? extends DefaultHighlightingConfiguration> bindHighlightingConfiguration() {
		return MyDslHighlightingConfiguration.class;
	}

	public void configureMatchingTagMarker(com.google.inject.Binder binder) {
		binder.bind(IXtextEditorCallback.class)
				.annotatedWith(Names.named(TaskConstants.XTEXT_TASKS)).to( //$NON-NLS-1$
						XtextTaskCalculator.class);
	}

	public Class<? extends ITaskElementChecker> bindTaskElementChecker() {
		return MyDslTaskElementChecker.class;
	}

	@Override
	public void configureUiEncodingProvider(Binder binder) {
		binder.bind(IEncodingProvider.class)
				.annotatedWith(DispatchingProvider.Ui.class)
				.to(UTF8Provider.class);
	}

	public Class<? extends IEncodingProvider> bindIEncodingProvider() {
		return UTF8Provider.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator> bindAbstractJavaBasedContentProposalProvider$ReferenceProposalCreator() {
		return CustomReferenceProposalCreator.class;
	}
}
