/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.conversion.ValueConverterException;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.ui.editor.contentassist.ConfigurableCompletionProposal;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator;
import org.eclipse.xtext.ui.editor.hover.IEObjectHover;

import com.google.common.base.Function;
import com.google.common.base.Predicate;
import com.google.inject.Inject;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {

	public ReferenceProposalCreator getCrossReferenceProposalCreator() {
		return super.getCrossReferenceProposalCreator();
	}
	
	@Override
	protected Function<IEObjectDescription, ICompletionProposal> getProposalFactory(final String ruleName,
			final ContentAssistContext contentAssistContext) {

		return new org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.DefaultProposalCreator(contentAssistContext, ruleName, getQualifiedNameConverter()) {
			
			@Inject
			private IEObjectHover hover;
			
			@Override
			public ICompletionProposal apply(IEObjectDescription candidate) {
				if (candidate == null)
					return null;
				ICompletionProposal result = null;
				String proposal = getQualifiedNameConverter().toString(candidate.getName());
				if (ruleName != null) {
					try {
						proposal = getValueConverter().toString(proposal, ruleName);
					} catch (ValueConverterException e) {
						return null;
					}
				}
				EObject objectOrProxy = candidate.getEObjectOrProxy();
				StyledString displayString = getStyledDisplayString(candidate);
				Image image = getImage(objectOrProxy);
				result = createCompletionProposal(proposal, displayString, image, contentAssistContext);
				if (result instanceof ConfigurableCompletionProposal) {
					((ConfigurableCompletionProposal) result).setAdditionalProposalInfo(objectOrProxy);
					((ConfigurableCompletionProposal) result).setHover(hover);
				}
				getPriorityHelper().adjustCrossReferencePriority(result, contentAssistContext.getPrefix());
				return result;
			}
			
			protected StyledString getStyledDisplayString(IEObjectDescription description) {
				return getStyledDisplayString(description.getEObjectOrProxy(),
						description.getEClass().getEPackage().getName() + "." + description.getName(),
						description.getEClass().getEPackage().getName() + "." + description.getName());
			}
			
			protected StyledString getStyledDisplayString(EObject element, String qualifiedName, String shortName) {
				return new StyledString(getDisplayString(element, qualifiedName, shortName));
			}
		};
	}
}
